name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment File
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" > .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env # Use >> to append instead of overwrite
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "LOG_CHANNEL=${{ secrets.LOG_CHANNEL }}" >> .env
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env
          # Include other necessary environment variables

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Optionally, run Laravel specific commands like migration, seed, etc.
      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache

      - name: Build Docker Image
        run: docker-compose up -d --build

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/html"

      - name: SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html
            docker-compose down
            docker-compose up -d --build
